server:
  port: 7777
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-3bven5g4.sql.tencentcdb.com:21195/intellicreation?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: IntelliCreation@2024
    hikari:
      # 连接池
      pool-name: DateHikariCP
      # 最小空闲连接出
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 连接池返回的连接自动提交
      auto-commit: true
      # 连接池最大存活时间
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
#  servlet:
#    multipart:
#      max-file-size: 2MB
#      max-request-size: 5MB
    freemarker:
      cache: false
  tencent:
    secretId: AKIDTm2OdhfZSBkCYpxBIKLF3k8TiprlbP6h
    secretKey: b5Uq9Qet4CMVbfeXGnGveI5xphZhsz3L
    region: ap-shanghai
    bucketName: intellicreation-1317922175
    path: https://intellicreation-1317922175.cos.ap-shanghai.myqcloud.com
    prefix: intellicreation
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
security:
  ignored:
    urls:
      - /member/login
      - /swagger-ui.html
      - /v2/**
      - /webjars/**
      - /swagger-resources/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
logstash:
  host: localhost
logging:
  level:
    root: debug

